export const movies = [
  {
    name: "Um Sonho de Liberdade",
    originalName: "The Shawshank Redemption",
    description:
      "Após ser condenado por um crime que não cometeu, um homem constrói uma amizade e preserva a esperança dentro de uma prisão corrupta.",
    status: "lançado",
    releaseDate: "1994-09-23",
    budget: 25000000,
    revenue: 28341469,
    banner: "https://image.tmdb.org/t/p/w1280/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    genres: ["Drama"],
    director: "Frank Darabont",
    durationMinutes: 142,
    rating: 9.3,
  },
  {
    name: "O Poderoso Chefão",
    originalName: "The Godfather",
    description:
      "A saga da família Corleone, sua ascensão ao poder e os dilemas morais do crime organizado.",
    status: "lançado",
    releaseDate: "1972-03-24",
    budget: 6000000,
    revenue: 246120986,
    banner: "https://image.tmdb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    genres: ["Crime", "Drama"],
    director: "Francis Ford Coppola",
    durationMinutes: 175,
    rating: 9.2,
  },
  {
    name: "Batman: O Cavaleiro das Trevas",
    originalName: "The Dark Knight",
    description:
      "Batman confronta o caos trazido pelo Coringa, que testa os limites morais de Gotham e do herói.",
    status: "lançado",
    releaseDate: "2008-07-18",
    budget: 185000000,
    revenue: 1004558444,
    banner: "https://image.tmdb.org/t/p/w1280/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    genres: ["Ação", "Crime", "Drama"],
    director: "Christopher Nolan",
    durationMinutes: 152,
    rating: 9,
  },
  {
    name: "Pulp Fiction: Tempo de Violência",
    originalName: "Pulp Fiction",
    description:
      "Histórias interligadas de criminosos, boxeadores e gângsteres em Los Angeles, contadas de forma não linear.",
    status: "lançado",
    releaseDate: "1994-10-14",
    budget: 8000000,
    revenue: 213928762,
    banner: "https://image.tmdb.org/t/p/w1280/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
    genres: ["Crime", "Drama"],
    director: "Quentin Tarantino",
    durationMinutes: 154,
    rating: 8.9,
  },
  {
    name: "Clube da Luta",
    originalName: "Fight Club",
    description:
      "Um narrador insone cria um clube clandestino de luta que evolui para algo muito mais perigoso.",
    status: "lançado",
    releaseDate: "1999-10-15",
    budget: 63000000,
    revenue: 100853753,
    banner: "https://image.tmdb.org/t/p/w1280/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg",
    genres: ["Drama", "Suspense"],
    director: "David Fincher",
    durationMinutes: 139,
    rating: 8.8,
  },
  {
    name: "A Origem",
    originalName: "Inception",
    description:
      "Um ladrão especializado em extrair segredos por meio dos sonhos recebe a missão de plantar uma ideia na mente de alguém.",
    status: "lançado",
    releaseDate: "2010-07-16",
    budget: 160000000,
    revenue: 829895144,
    banner: "https://image.tmdb.org/t/p/w1280/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg",
    genres: ["Ação", "Ficção Científica", "Suspense"],
    director: "Christopher Nolan",
    durationMinutes: 148,
    rating: 8.8,
  },
  {
    name: "Interestelar",
    originalName: "Interstellar",
    description:
      "Uma missão interestelar busca um novo lar para a humanidade enquanto explora as leis do tempo e do espaço.",
    status: "lançado",
    releaseDate: "2014-11-07",
    budget: 165000000,
    revenue: 701729206,
    banner: "https://image.tmdb.org/t/p/w1280/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    genres: ["Ficção Científica", "Drama"],
    director: "Christopher Nolan",
    durationMinutes: 169,
    rating: 8.6,
  },
  {
    name: "Parasita",
    originalName: "Parasite",
    description:
      "Uma família pobre infiltra-se na vida de uma família rica, desencadeando eventos imprevisíveis e sombrios.",
    status: "lançado",
    releaseDate: "2019-05-30",
    budget: 11400000,
    revenue: 258816000,
    banner: "https://image.tmdb.org/t/p/w1280/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    genres: ["Drama", "Suspense"],
    director: "Bong Joon-ho",
    durationMinutes: 132,
    rating: 8.6,
  },
  {
    name: "A Viagem de Chihiro",
    originalName: "Spirited Away",
    description:
      "Uma jovem menina entra num mundo mágico de espíritos e precisa encontrar uma maneira de salvar seus pais.",
    status: "lançado",
    releaseDate: "2001-07-20",
    budget: 19000000,
    revenue: 383400000,
    banner: "https://image.tmdb.org/t/p/w1280/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    genres: ["Animação", "Fantasia"],
    director: "Hayao Miyazaki",
    durationMinutes: 125,
    rating: 8.6,
  },
  {
    name: "O Senhor dos Anéis: A Sociedade do Anel",
    originalName: "The Lord of the Rings: The Fellowship of the Ring",
    description:
      "Um jovem hobbit embarca numa jornada para destruir um poderoso anel antes que ele corrompa o mundo.",
    status: "lançado",
    releaseDate: "2001-12-19",
    budget: 93000000,
    revenue: 897700000,
    banner: "https://image.tmdb.org/t/p/w1280/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    genres: ["Aventura", "Fantasia"],
    director: "Peter Jackson",
    durationMinutes: 178,
    rating: 8.8,
  },
  {
    name: "Matrix",
    originalName: "The Matrix",
    description:
      "Um programador descobre que a realidade é uma simulação e junta-se à resistência para libertar a humanidade.",
    status: "lançado",
    releaseDate: "1999-03-31",
    budget: 63000000,
    revenue: 463517383,
    banner: "https://image.tmdb.org/t/p/w1280/p96dm7sCMn4VYAStA6siNz30G1r.jpg",
    genres: ["Ação", "Ficção Científica"],
    director: "Lana Wachowski, Lilly Wachowski",
    durationMinutes: 136,
    rating: 8.7,
  },
  {
    name: "Forrest Gump: O Contador de Histórias",
    originalName: "Forrest Gump",
    description:
      "A história de um homem simples que, sem querer, influencia vários eventos históricos enquanto persegue seu amor de infância.",
    status: "lançado",
    releaseDate: "1994-07-06",
    budget: 55000000,
    revenue: 678200000,
    banner: "https://image.tmdb.org/t/p/w1280/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    genres: ["Drama", "Romance"],
    director: "Robert Zemeckis",
    durationMinutes: 142,
    rating: 8.8,
  },
  {
    name: "O Silêncio dos Inocentes",
    originalName: "The Silence of the Lambs",
    description:
      "Uma jovem agente do FBI pede ajuda a um canibal encarcerado para capturar um serial killer.",
    status: "lançado",
    releaseDate: "1991-02-14",
    budget: 19000000,
    revenue: 272742922,
    banner: "https://image.tmdb.org/t/p/w1280/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
    genres: ["Crime", "Suspense", "Terror"],
    director: "Jonathan Demme",
    durationMinutes: 118,
    rating: 8.6,
  },
  {
    name: "A Lista de Schindler",
    originalName: "Schindler's List",
    description:
      "A história real de Oskar Schindler, que salvou centenas de judeus do Holocausto empregando-os em suas fábricas.",
    status: "lançado",
    releaseDate: "1993-12-15",
    budget: 22000000,
    revenue: 322161245,
    banner: "https://image.tmdb.org/t/p/w1280/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    genres: ["Drama", "Histórico"],
    director: "Steven Spielberg",
    durationMinutes: 195,
    rating: 8.9,
  },
  {
    name: "A Rede Social",
    originalName: "The Social Network",
    description:
      "A ascensão do Facebook e os conflitos legais e pessoais por trás da sua criação.",
    status: "lançado",
    releaseDate: "2010-10-01",
    budget: 40000000,
    revenue: 224920315,
    banner: "https://image.tmdb.org/t/p/w1280/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
    genres: ["Drama", "Biografia"],
    director: "David Fincher",
    durationMinutes: 120,
    rating: 7.7,
  },
  {
    name: "Gladiador",
    originalName: "Gladiator",
    description:
      "Um general romano traído busca vingança contra o imperador que destruiu sua família.",
    status: "lançado",
    releaseDate: "2000-05-05",
    budget: 103000000,
    revenue: 460583960,
    banner: "https://image.tmdb.org/t/p/w1280/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    genres: ["Ação", "Drama", "Histórico"],
    director: "Ridley Scott",
    durationMinutes: 155,
    rating: 8.5,
  },
  {
    name: "O Grande Truque",
    originalName: "The Prestige",
    description:
      "Dois mágicos rivais entram numa competição obsessiva para criar o melhor truque de todos os tempos.",
    status: "lançado",
    releaseDate: "2006-10-20",
    budget: 40000000,
    revenue: 109676311,
    banner: "https://image.tmdb.org/t/p/w1280/2ZOzyhoW08neG27DVySMCcq2emd.jpg",
    genres: ["Drama", "Mistério", "Ficção Científica"],
    director: "Christopher Nolan",
    durationMinutes: 130,
    rating: 8.5,
  },
  {
    name: "Whiplash: Em Busca da Perfeição",
    originalName: "Whiplash",
    description:
      "Um jovem baterista enfrenta um professor impiedoso enquanto busca a grandeza musical.",
    status: "lançado",
    releaseDate: "2014-10-10",
    budget: 3300000,
    revenue: 48900000,
    banner: "https://image.tmdb.org/t/p/w1280/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    genres: ["Drama", "Música"],
    director: "Damien Chazelle",
    durationMinutes: 106,
    rating: 8.5,
  },
  {
    name: "La La Land: Cantando Estações",
    originalName: "La La Land",
    description:
      "Um músico e uma atriz lutam para conciliar amor e ambição na cidade dos sonhos.",
    status: "lançado",
    releaseDate: "2016-12-09",
    budget: 30000000,
    revenue: 446936000,
    banner: "https://image.tmdb.org/t/p/w1280/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    genres: ["Musical", "Romance"],
    director: "Damien Chazelle",
    durationMinutes: 128,
    rating: 8,
  },
  {
    name: "O Rei Leão",
    originalName: "The Lion King",
    description:
      "A jornada de um jovem leão em se tornar rei, enfrentando traições e aprendendo sobre responsabilidade.",
    status: "lançado",
    releaseDate: "1994-06-24",
    budget: 45000000,
    revenue: 968483777,
    banner: "https://image.tmdb.org/t/p/w1280/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
    genres: ["Animação", "Aventura", "Drama"],
    director: "Roger Allers, Rob Minkoff",
    durationMinutes: 88,
    rating: 8.5,
  },
  {
    name: "Titanic",
    originalName: "Titanic",
    description:
      "Um romance épico a bordo do navio Titanic que termina em tragédia quando o navio colide com um iceberg.",
    status: "lançado",
    releaseDate: "1997-12-19",
    budget: 200000000,
    revenue: 2187463944,
    banner: "https://image.tmdb.org/t/p/w1280/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    genres: ["Romance", "Drama"],
    director: "James Cameron",
    durationMinutes: 195,
    rating: 7.8,
  },
  {
    name: "Avatar",
    originalName: "Avatar",
    description:
      "Em um mundo alienígena, um ex-fuzileiro adapta-se ao corpo de um nativo para descobrir a beleza e os conflitos locais.",
    status: "lançado",
    releaseDate: "2009-12-18",
    budget: 237000000,
    revenue: 2847246203,
    banner: "https://image.tmdb.org/t/p/w1280/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg",
    genres: ["Ficção Científica", "Aventura"],
    director: "James Cameron",
    durationMinutes: 162,
    rating: 7.8,
  },
  {
    name: "Os Infiltrados",
    originalName: "The Departed",
    description:
      "Um jogo mortal de gato e rato entre policiais infiltrados e criminosos em Boston.",
    status: "lançado",
    releaseDate: "2006-10-06",
    budget: 90000000,
    revenue: 291465034,
    banner: "https://image.tmdb.org/t/p/w1280/nT97ifVT2J1yMQmeq20Qblg61T.jpg",
    genres: ["Crime", "Drama", "Thriller"],
    director: "Martin Scorsese",
    durationMinutes: 151,
    rating: 8.5,
  },
  {
    name: "Django Livre",
    originalName: "Django Unchained",
    description:
      "Um escravo liberto e um caçador de recompensas unem forças para resgatar a esposa do escravo de um brutal fazendeiro.",
    status: "lançado",
    releaseDate: "2012-12-25",
    budget: 100000000,
    revenue: 425368238,
    banner: "https://image.tmdb.org/t/p/w1280/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
    genres: ["Western", "Drama"],
    director: "Quentin Tarantino",
    durationMinutes: 165,
    rating: 8.4,
  },
  {
    name: "Mad Max: Estrada da Fúria",
    originalName: "Mad Max: Fury Road",
    description:
      "Num mundo pós-apocalíptico, uma mulher e um homem lutam por liberdade enquanto fogem de um tirano.",
    status: "lançado",
    releaseDate: "2015-05-15",
    budget: 150000000,
    revenue: 378858340,
    banner: "https://image.tmdb.org/t/p/w1280/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
    genres: ["Ação", "Aventura"],
    director: "George Miller",
    durationMinutes: 120,
    rating: 8.1,
  },
  {
    name: "Blade Runner 2049",
    originalName: "Blade Runner 2049",
    description:
      "Num futuro distópico, um novo Blade Runner descobre um segredo que pode mergulhar a sociedade no caos.",
    status: "lançado",
    releaseDate: "2017-10-06",
    budget: 150000000,
    revenue: 259239658,
    banner: "https://image.tmdb.org/t/p/w1280/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    genres: ["Ficção Científica", "Thriller"],
    director: "Denis Villeneuve",
    durationMinutes: 164,
    rating: 8,
  },
  {
    name: "Coringa",
    originalName: "Joker",
    description:
      "A origem sombria de Arthur Fleck e sua transformação no icônico vilão Coringa.",
    status: "lançado",
    releaseDate: "2019-10-04",
    budget: 55000000,
    revenue: 1074251311,
    banner: "https://image.tmdb.org/t/p/w1280/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    genres: ["Crime", "Drama"],
    director: "Todd Phillips",
    durationMinutes: 122,
    rating: 8.4,
  },
  {
    name: "Corra!",
    originalName: "Get Out",
    description:
      "Ao visitar a família de sua namorada branca, um jovem negro descobre segredos perturbadores.",
    status: "lançado",
    releaseDate: "2017-02-24",
    budget: 4500000,
    revenue: 255407969,
    banner: "https://image.tmdb.org/t/p/w1280/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    genres: ["Terror", "Suspense"],
    director: "Jordan Peele",
    durationMinutes: 104,
    rating: 7.7,
  },
  {
    name: "O Grande Hotel Budapeste",
    originalName: "The Grand Budapest Hotel",
    description:
      "As aventuras de um concierge e seu jovem protegido em um hotel europeu durante o período entre-guerras.",
    status: "lançado",
    releaseDate: "2014-03-07",
    budget: 25000000,
    revenue: 174600000,
    banner: "https://image.tmdb.org/t/p/w1280/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    genres: ["Comédia", "Drama"],
    director: "Wes Anderson",
    durationMinutes: 99,
    rating: 8.1,
  },
  {
    name: "Moonlight: Sob a Luz do Luar",
    originalName: "Moonlight",
    description:
      "A vida de um jovem negro cresce em três fases enquanto ele lida com identidade, família e amor.",
    status: "lançado",
    releaseDate: "2016-10-21",
    budget: 4000000,
    revenue: 65365687,
    banner: "https://image.tmdb.org/t/p/w1280/rcICfiL9fvwRjoWHxW8QeroLYrJ.jpg",
    genres: ["Drama"],
    director: "Barry Jenkins",
    durationMinutes: 111,
    rating: 7.4,
  },
];
